import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, FC } from 'react';

interface HomeInterface {
  municipalities: any
}

const Home: FC<HomeInterface> = ({municipalities}) => {

  useEffect(() => {
      console.log('hey');
      console.log(municipalities);
  }, [municipalities])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World!</h1>
    </div>
  )
}

export default Home
